### ISSUE TITLE
gguf版本的量化選項

### ISSUE THREAD

**Issue by CRGBS** [HIT-SCIR/huozi#10]
可以多提供一些量化選項出來嗎
例如fp16
以及我想要的Q5_K_M

**Comment by jubgjf** [comment]
- 由于我们是使用bf16训练，建议您直接按照bf16格式进行加载，无需转换到fp16
- 由于llama.cpp的量化格式众多，我们目前只提供了q4_0和q2_k两种相对主流的量化格式，您也可以参考文档中的[这部分](https://github.com/HIT-SCIR/huozi#step-2-%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2%E5%8F%AF%E9%80%89)自行进行量化
