### ISSUE TITLE
请问指令微调数据是由哪些数据组成的呀？

### ISSUE THREAD

**Issue by Macvh** [HIT-SCIR/huozi#11]
请问指令微调数据集大小，组成信息以及预处理方式公开了吗

**Comment by jubgjf** [comment]
微调数据集包括一部分私有数据集，暂无全部公开的计划。

我们使用的公开数据集包括：
- [Skywork/SkyPile-150B](https://huggingface.co/datasets/Skywork/SkyPile-150B)（回放，部分采样）
- [DKYoon/SlimPajama-6B](https://huggingface.co/datasets/DKYoon/SlimPajama-6B)（回放，部分采样）
- [shareAI/ShareGPT-Chinese-English-90k](https://huggingface.co/datasets/shareAI/ShareGPT-Chinese-English-90k)
- [theblackcat102/evol-codealpaca-v1](https://huggingface.co/datasets/theblackcat102/evol-codealpaca-v1)

私有数据集包括：
- 各类传统NLP任务的指令数据
- 安全数据

数据集总量为30万条。我们对数据集内部的模型身份信息做了过滤
