### ISSUE TITLE
微调数据集

### ISSUE THREAD

**Issue by a171232886** [HIT-SCIR/huozi#12]
不愧是哈工大，Chinese-Mixtral-8x7B和huozi都是了不起的工作。

huozi3的指令微调数据集会公开吗？

另外，“活字”这个名字起的真好。

**Comment by jubgjf** [comment]
十分感谢您的支持！

微调数据集相关说明可以参考[此issue](https://github.com/HIT-SCIR/huozi/issues/11#issuecomment-1973113428)
